### PR TITLE
Add 2018-03 event

### PR DESCRIPTION
**Pull request by killercup**
cf. #48

### CODE REVIEW

**Review by Florob — APPROVED** [review]
LGTM, a bit surprised file name and title are different.
I think I'd have objected to "bring an oscilloscope" as title on the grounds of it not being sufficient/useful for either talk, and some people just taking things too literal.

**Comment by killercup** [comment]
The (great) title seemed too long for a URL so I tried to compress the joke a bit ;) I can totally change it, though! Do you have a suggestion?

**Comment by Florob** [comment]
How about `2018-03-12-what-are-you-plotting.md`

**Comment by killercup** [comment]
I like it! Changed, and merged!

**Pull request merged**
