### PR TITLE
Reorganize event page

### LINKED ISSUE #17: Feedback regarding multiple announcements on rust.cologne
@killercup You asked for feedback. :-)

I see two problems
1. The titles are very long
2. future meetups are not very visible

Suggestions:
* using ISO-international dates `YYYY-MM-DD`, i.e. `2016-11-16` instead of american `Nov. 16th, 2016`
* adding the timezone `19:00 CET`
* removing the location from the title to make it shorter [it's least important and currently alsways the same plus it's very redundant for the next meetup layout with directions and maps following the title]
* if possible move the date and time into a slightly smaller subtitle to make the titles even shorter, while retaining some focus on the dates
* Increse the fonts for 'more future meetups: ...' to match 'next meetup: ...'

What do you think about this?

### PR DESCRIPTION
**Pull request by killercup**
Wants to fix #17

### CODE REVIEW

**Comment by killercup** [comment]
@colin-kiegel, I tried to implement what you suggested in #17, with a few minor adjustments.

One of the main _internal_ changes is that the location data is now a separate hash map (`_data/locations.yml`) so we don't need to repeat the address and direction information in every event.

You can quite easily try this out yourself by checking out the feature branch and running `jekyll s` (assuming you somewhat recently did `gem install github-pages`). Nevertheless, here are a few screenshots:

bildschirmfoto 2016-11-13 um 14 11 22

bildschirmfoto 2016-11-13 um 14 11 51

bildschirmfoto 2016-11-13 um 14 12 24

**Comment by killercup** [comment]
Seeing this, I'm thinking about picking up the inverse style (white on black) of the talk headers for more elements. Maybe as a 'label' style for the "Next Meetup"-style headers?

**Comment by colin-kiegel** [comment]
LGTM

Inverted Labels could indeed work. I would then try to shorten them to and probably make the background only as wide as the text. This would also reduce some repetition of the word meetup.   
- next
- upcoming
- previous

On a side note we could also have a look at our mobile break point. It feels like we could raise it a bit and switch to one column layout earlier.

How do you want to proceed? If you want to do further iterations I could give some more feedback this evening/tomorrow based on some experimenting with font sizes and the like.

**Comment by killercup** [comment]
> I would then try to shorten them to and probably make the background only as wide as the text.

Yep! Have a look at the (zoomed out) start page right now:

bildschirmfoto 2016-11-13 um 15 33 55

I like it. I'm not sure if the talks should be as prominent, but they are kinda important (I assume people come mostly because we have interesting topics to talk about!).

> On a side note we could also have a look at our mobile break point. It feels like we could raise it a bit and switch to one column layout earlier.

Already did this! :) (The breakpoint right now is 40rem at 18px default font size, so around 720px.)

> How do you want to proceed? If you want to do further iterations I could give some more feedback this evening/tomorrow based on some experimenting with font sizes and the like.

I'm in no hurry. I probably have some more time this evening but will be in meetings most of tomorrow.

**Comment by colin-kiegel** [comment]
@killercup I suggest these minor changes ([patch.txt](https://github.com/Rustaceans/rust-cologne/files/590190/patch.txt))
- make labels smaller in y-direction (they look a bit like buttons with their current size)
- move labels closer to the headlines (the current spacing between label and headline does not suggest the label to be attached to the headline IMO)

screenshot from 2016-11-14 19-46-31

screenshot from 2016-11-14 19-46-46

**Comment by colin-kiegel** [comment]
Hm .. maybe a last thing:
- the spacing between these sections are different `TITLE` `DESCRIPTION` `TALK-LIST` `DIRECTIONS`. It might look better, if they were all as small as between `TITLE` and `DESCRIPTION`

You can see the _different_ spacing here:

screenshot from 2016-11-14 19-46-31

**Comment by killercup** [comment]
Sounds good. I'll try to update this later today.

Memo to self: update event page description meta tag to contain event
details.
Colin Kiegel notifications@github.com schrieb am Mo. 14. Nov. 2016 um
20:02:

**Comment by killercup** [comment]
@colin-kiegel updated with your suggestions.

@Rustaceans/organizers-cologne, are you okay with these changes?

**Comment by badboy** [comment]
I only skimmed the discussion, but took a look at the screenshots. I trust your judgment and web skillz on that more than mine, so please go ahead.

**Pull request merged**
