### PR TITLE
Add November event

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by killercup** [comment]
Quick draft for #68.

@pizzamig, added your talk according to your comment.

@gnunicorn, I bascially just pasted in what you wrote in https://github.com/Rustaceans/rust-cologne/issues/68#issuecomment-431689122 so I had the two talks listed -- let me know what to change/replace.

**Comment by gnunicorn** [comment]
@killercup didn't see this before. I've added more content on https://github.com/Rustaceans/rust-cologne/issues/68#issuecomment-432242393

**Comment by killercup** [comment]
@gnunicorn updated with your texts :)

**Comment by mre** [comment]
My god, these meetups keep getting better and better. ❤️ 
@killercup, if I should summon the [hello](https://github.com/hello-rust/hello), just ping me.

**Review by Florob — APPROVED** [review]

**Comment by killercup** [comment]
🎉  https://rust.cologne/2018/11/07/freebsd-and-networking.html

@mre!

release-the-kraken-32862457

**Comment by mre** [comment]
👋 [Reddit](https://www.reddit.com/r/rust/comments/9qq0zi/rusty_freebsd_and_networking/)
👋 [Forum](https://users.rust-lang.org/t/cologne-germany-rusty-freebsd-and-networking-on-2018-11-07/21554)

**Pull request merged**
