### PR TITLE
Add glorious logo by @mre (#9)

### PR DESCRIPTION
**Pull request by killercup**
I warned you, didn't I?

bildschirmfoto 2017-02-19 um 15 52 12
bildschirmfoto 2017-02-19 um 15 52 07
bildschirmfoto 2017-02-19 um 15 52 02
bildschirmfoto 2017-02-19 um 15 52 30

### CODE REVIEW

**Comment by badboy** [comment]
:shipit:

**Comment by killercup** [comment]
I'll replace the favicon and add an open graph image (shown on twitter and facebook) as well.

**Review by Florob — APPROVED** [review]
Looks good to me. I also quite like having the cathedral in a different color, but no strong preference there.

**Review by colin-kiegel — APPROVED** [review]
:+1: Thx a lot for your effort @mre and @killercup.

**Comment by killercup** [comment]
🎉

**Pull request merged**
