### PR TITLE
No more embeds

### LINKED ISSUE #52: Make Youtube and Google Maps embed opt-in
To make the website faster and so we don't have to worry about GDPR we should make the google embeds optional, i.e., show a preview image and load the stuff only after explicitly clicking on it. I'm not even sure we need to load this as an embed. (I guess people who know about Rust are able to use tabs in a browser.)

### PR DESCRIPTION
**Pull request by killercup**
This removes any third-party embeds.

First up: Maps. Google Maps is by far the best-looking and most comfortable map solution out there. Period. And, to my surprise, it turns out there are no even semi-good-looking OpenStreetMap providers out there that allow you to download and host static images of their maps for free. (Mapbox is the only one I could find that actually looks kinda good, but they require you to load the maps from their server coupled with an API key.)

So, I went with with:

bildschirmfoto 2018-06-06 um 17 20 10

And the second embed we use: That video on the start page. I just replaced it with an image I threw together (one more cog):

bildschirmfoto 2018-06-06 um 17 21 13

I hope that's alright with you.

Fixes #52

### CODE REVIEW

**Comment by Florob** [comment]
I actually kind of disagree on the maps thing. Google maps has become increasingly unusable for me. Starting with disorienting zoom and now apparently having a no contrast color scheme that might as well be a gray blob. I also agree that OSM is severely lacking in terms of frontends and stylesheets though.
That said I don't find OSM's default render disgusting enough to prefer no image at all. But in the end people will likely click though to a fully featured map anyway. I don't really mind either way.

I think it would be nice if we would link to some non-google services though.
For maps I'd at least like to be able to choose OSM.
For videos from my POV linking to https://media.ccc.de/c/rustmcb makes more sense anyway. The original upload has always ended up there and I don't see that changing any time soon.

**Comment by killercup** [comment]
I agree with not linking to Google services by default.

> That said I don't find OSM's default render disgusting enough to prefer no image at all. But in the end people will likely click though to a fully featured map anyway. I don't really mind either way.

A concrete issue is this: I want to show a map with relevant street names and enough of the surrounding area that also works in a small context. OSM gives me this:

bildschirmfoto 2018-06-06 um 22 15 27

which is not super bad but also not really that helpful for all the little details it contains. GMaps sure strips a lot of data but what they produce is quite pretty and very easy to read (and actually in good resolution!):

bildschirmfoto 2018-06-06 um 22 12 20

For comparison, mapbox has [a very nice OSM layer](https://api.mapbox.com/styles/v1/mapbox/streets-v9.html?title=true&access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA#14.03/50.95208/6.91694) but it is not free:

bildschirmfoto 2018-06-06 um 22 17 49

But I guess it's not that important anyway. What site would you link to? I wanted to keep GMaps because it has pretty good navigation.

> For videos from my POV linking to https://media.ccc.de/c/rustmcb makes more sense anyway. The original upload has always ended up there and I don't see that changing any time soon.

I thought about that, but there are two downsides and another thing:

1. The channel works better on mobile. Not sure how relevant that is.
2. The youtube channel has stuff from other meetups and conferences!
3. If there are recordings for the ThoughtWorks meetup, would they end up on media.ccc.de, too?

We could link to both, but I'm not sure people would really appreciate that if they just want to watch Rust talks.

**Comment by Florob** [comment]
Maps:
I'm definitely not saying to ditch Google Maps. It probably should even be the first option. The problem is really that OSM doesn't even easily give you access to data about POIs that it actually has.
But it would be nice to also have a "Show on OpenStreeMap" link, linking to something like `https://www.openstreetmap.org/?mlat=50.95041&mlon=6.91295`. Probably templated on the coordinates.

Video:
I can't claim YouTube doesn't work better on mobile. But media.ccc.de also works fine on my 3 years old phone on a moderate 3G connection and has audio only versions available if you're very bandwidth constrained. Granted YouTube has video snippets for super low bandwidth, but you won't exactly be able to read slides or recognize a speaker on them.

I'm also not convinced that for the Rust Cologne website, where we're pointing to "more videos from this meetup" it is important to have other Rust content on the same channel/platform. In the past our videos were released on YouTube significantly later, which means it was not really ideal for people looking for recordings of recent talks. I'm saying "was" because ever since RustFest I could in theory publish them on both platforms in parallel. I guess I'd just have ask if I may.

Video at ThoughtWorks is an interesting point, but I'm not sure how that factors into this argument. If ThoughtWorks is doing video it fundamentally ends up wherever they put it, under whatever license they please. Which could mean we can't legally publish it on either platform. If they just give us a file and a reasonably permissive license, it's up to us where we put it. If we're doing video ourselves, which is not entirely implausible considering how close it is to the C4, it would end up on media.ccc.de and probably later on YouTube.

I'll be frank I'm definitely getting super defensive about this. I help running media.ccc.de and produce content for it because it's something I fundamentally believe in. It's a platform providing free (conference) recordings and not collecting data about its users. Some people do appreciate it for that. Most people appreciate the video more than the platform though, and just want their $market_leader. It'd be interesting what happens when $market_leader> is no longer YouTube, because content creators are finally fed up with them.
At this point in time for me it's pretty much media.ccc.de, a platform I have a lot of control over vs. a YouTube channel that I cannot really upload to and where I can't edit metadata.

**Comment by killercup** [comment]
> The problem is really that OSM doesn't even easily give you access to data about POIs that it actually has. But it would be nice to also have a "Show on OpenStreeMap" link […]

You can actually link to POIs ("nodes")! Searching for Chaos Computer Club Cologne gave me a <https://www.openstreetmap.org/node/1446603282>. I'll add some links!

> I'm also not convinced that for the Rust Cologne website, where we're pointing to "more videos from this meetup" it is important to have other Rust content on the same channel/platform. […] I help running media.ccc.de and produce content for it because it's something I fundamentally believe in. […] At this point in time for me it's pretty much media.ccc.de, a platform I have a lot of control over vs. a YouTube channel that I cannot really upload to and where I can't edit metadata.

Very good points regarding video, thanks for writing that. I really admire that media.ccc.de is a thing that does not just exist somewhere but actually works very well and has really amazing content, too. My main motivation was to give people an entry point to more Rust video content, but you are right, that is not the same as "other videos from us".

Is it okay if I add two links -- "More Rust Cologne videos" and "Videos from Rust conferences other meetups"?

> If ThoughtWorks is doing video it fundamentally ends up wherever they put it, under whatever license they please. Which could mean we can't legally publish it on either platform.

FIY, if they chose youtube, I think the Rust channel can add videos from their channel to the Rust Cologne playlist.

**Comment by Florob** [comment]
> You can actually link to POIs ("nodes")! Searching for Chaos Computer Club Cologne gave me a https://www.openstreetmap.org/node/1446603282.

I was actually aware of that. I didn't think it worked as well as the customary blue mark, but seeing it again this might actually work for us.
OT: My gripe with the OSM UI is more that a) selecting nodes is a pretty hidden feature, b) in that mode you can select any node, not just what most would consider POI.

> Is it okay if I add two links -- "More Rust Cologne videos" and "Videos from Rust conferences other meetups"?

Sure, that is fine with me. Maybe throw an "and" in the second one though.

**Comment by killercup** [comment]
> OT: My gripe with the OSM UI is more that a) selecting nodes is a pretty hidden feature, b) in that mode you can select any node, not just what most would consider POI.

Fun fact: Some of the other locations are "relations" and not "nodes". I can see why the Stadtpark is not a single node, but the coworking space?

> Maybe throw an "and" in the second one though.

It's rendered as two paragraphs:

bildschirmfoto 2018-06-08 um 17 03 26

(Just merge if you like it)

**Comment by Florob** [comment]
>> Maybe throw an "and" in the second one though.
>
> It's rendered as two paragraphs:

That was wrt. to "Videos from Rust conferences **and** other meetups", which is not currently in the PR AFAICT.

**Comment by killercup** [comment]
Ah right, sorry. Added.

**Comment by Florob** [comment]
Thank you. I really appreciate the work you have put into this, despite all my complaining.

**Comment by killercup** [comment]
No, thank you for complaining! This is better than what I had initially :)

**Pull request merged**
